{% set name = "minepy" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7455c5d2edee63b660593343d2876bf5e0a2e41cfd74a29d9e42fd00022f39f9

build:
  number: 3
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy >=1.3.0
    - pip
    - python
  run:
    - numpy >=1.3.0
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - minepy

about:
  home: http://minepy.readthedocs.io
  license: GPL-3.0-only
  license_family: LGPL
  license_file: gpl-3.0.txt
  summary: minepy - Maximal Information-based Nonparametric Exploration
  doc_url: http://minepy.readthedocs.io
  dev_url: https://github.com/minepy/minepy

extra:
  recipe-maintainers:
    - philip-khor
